### ISSUE TITLE
Cyrillic glyphs

### ISSUE THREAD

**Issue by rellikmil** [kemie/Bellota-Font#2]

**Comment by preciselykem** [comment]
Would love some help in this as I have little experience in designing cyrillic

**Comment by kemie** [comment]
Would love some help in this as I have little experience in designing Cyrillic

**Comment by rellikmil** [comment]
I will help with all I can, but I haven`t Mac, Glyphs and Illustrator, so I will use FontForge and Inkscape (because UFO). And yes, please add original Glyphs project files (I will create list of true open source fonts on GitHub)

**Comment by kemie** [comment]
I'll upload the .glyphs, for sure. If you can help me with the basic shapes in .ufo I can then integrate into glyphs.

**Comment by rellikmil** [comment]
![изображение](https://user-images.githubusercontent.com/24569064/63101484-c945ec00-bf81-11e9-9c7c-89ffa7aca9ed.png)
Yeah, it`s not simple as I think
How draw letter Д?

**Comment by kemie** [comment]
@den32ds I just uploaded the first draft of Cyrillic glyphs. can you take a look and tell me how they're looking?

**Comment by rellikmil** [comment]
@kemie I see, you improved П, excellent work, really, now you need to add "serifs" (serifs in sans-serif ehm) and improve capital Ы
![изображение](https://user-images.githubusercontent.com/24569064/64461411-cb751380-d105-11e9-8ebc-f5d38e1aa64e.png)
And you make non-direct Л, I`m surprised
When you update README, write in Russian "Великое начинается с малого"

**Comment by rellikmil** [comment]
And ya`know when I can find information about OpenType features? How prescribe them etc.

**Comment by rellikmil** [comment]
![изображение](https://user-images.githubusercontent.com/24569064/65379673-60fece80-dcd4-11e9-9f1a-a3cf8c0d44d4.png)
Lower П is upper П

**Comment by kemie** [comment]
Fixed! 

(for opentype check http://opentypecookbook.com/)
