### ISSUE TITLE
Outline misbehaviour

### ISSUE THREAD

**Issue by yanone** [kemie/Bellota-Font#4]
Hi, I had a quick look and found the following problem which I would like to ask you to address before I proceed:

The `a` has a corner issue in the Bold Italic, see screenshot: <img width="1792" alt="Bildschirmfoto 2019-10-25 um 14 51 01" src="https://user-images.githubusercontent.com/175386/67573632-1a6c1c00-f739-11e9-91e5-aa415ab5b98a.png">

**Comment by kemie** [comment]
Should be fixed with my latest push
