### ISSUE TITLE
Heavy Weight

### ISSUE THREAD

**Issue by Cdddo** [kemie/Bellota-Font#6]
I really like this font! But I was wondering if it would be possible to have a heavier weight?

**Comment by kemie** [comment]
I've been thinking about this too! I'll put it on my to-dos.

**Comment by kemie** [comment]
@Cdddo just to let you know i've started work on this. no promises on when it will be done, though
[Sneak peek](https://cln.sh/EAWnXZ)

**Comment by Cdddo** [comment]
@kemie that's great, looking forward to it!

**Comment by kemie** [comment]
@Cdddo a few years later, but Bellota & Bellota Text now come in weights from Thin to Black. 
![Bellota_weights](https://github.com/user-attachments/assets/5cc80312-9722-47b1-9b3e-5cafe9d2bb8a)

**Comment by kemie** [comment]
New version has up to an ExtraBold weight
